- name: Desplegar servidor web
  hosts: web
  become: true
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Subir sitio HTML
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hola desde CI/CD + Ansible</h1>"
